name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Xcode 11.4
      run: |
        sudo xcode-select -s /Applications/Xcode_11.4.app/Contents/Developer
        xcodebuild -version
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
