name: Swift Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  macos_build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Xcode 13.1
      run: |
        sudo xcode-select -s /Applications/Xcode_12.app/Contents/Developer
        xcodebuild -version
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
  swift_xenial:
    container: 
      image: swift:5.5-xenial
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: swift test --enable-test-discovery --sanitize=thread
  swift_bionic:
    container: 
      image: swift:5.5-bionic
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: swift test --enable-test-discovery --sanitize=thread
